# Generated by Django 4.2.1 on 2023-09-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_product_product_size_producttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='product_prize',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
