# Generated by Django 4.2.1 on 2023-09-03 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_productdetail_remove_product_discount_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.productdetail'),
        ),
    ]
